language: C
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - original-awk
    - gawk
    - busybox-static
    - mawk

install:
  - original-awk --version
  - gawk --version | head -n 1
  - busybox | head -n 1
  - mawk -W version 2>&1 | head -n 1

script: ./travis-test-all.sh

env:
  matrix:
    - AWKCMD=original-awk
    - AWKCMD=gawk
    - AWKCMD="busybox awk"
    - AWKCMD=mawk
